name: .NET CI

on:
  push:
    paths:
      - 'EventManagement/**'
    branches:
      - master
      - 'feature-*'
    paths-ignore:
      - '**.md'
      - 'Dockerfile'
      - 'docker/**'

  pull_request:
    paths:
      - 'EventManagement/**'
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'Dockerfile'
      - 'docker/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore EventManagement/dnaborshchikova_github.Bea.EventManagement.slnx

      - name: Build
        run: dotnet build EventManagement/dnaborshchikova_github.Bea.EventManagement.slnx --configuration Release

      - name: Run tests
        run: dotnet test EventManagement/dnaborshchikova_github.Bea.EventManagement.Tests --no-build --configuration Release --verbosity normal